# Generated by Django 5.2.8 on 2025-12-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tags_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='budget',
            new_name='price',
        ),
        migrations.AddField(
            model_name='project',
            name='price_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed-price')], default='fixed', max_length=20),
        ),
    ]
