# Generated by Django 5.2.8 on 2025-12-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_fill_project_details(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    overview = (
        "We need a crisp, conversion-focused landing page that aligns product messaging "
        "with a new visual identity. The work should include copy refinement, a modular "
        "layout system, and a responsive hero section."
    )
    responsibilities = (
        "Audit the current landing page and propose a new narrative flow.\n"
        "Design three hero variants with clear CTAs.\n"
        "Deliver desktop and mobile layouts in Figma."
    )
    requirements = (
        "Design system tokens for spacing, typography, and color.\n"
        "Final responsive layouts and a component library.\n"
        "Handoff checklist with assets and usage notes."
    )

    Project.objects.filter(project_overview__isnull=True).update(project_overview=overview)
    Project.objects.filter(project_overview="").update(project_overview=overview)
    Project.objects.filter(responsibilities__isnull=True).update(responsibilities=responsibilities)
    Project.objects.filter(responsibilities="").update(responsibilities=responsibilities)
    Project.objects.filter(requirements__isnull=True).update(requirements=requirements)
    Project.objects.filter(requirements="").update(requirements=requirements)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_client_and_freelancer_profiles"),
        ("projects", "0003_rename_budget_project_price_project_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_overview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="responsibilities",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What you will do (one item per line or markdown list)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Requirements of client (one item per line or markdown list)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="accounts.clientprofile",
            ),
        ),
        migrations.RunPython(forwards_fill_project_details, migrations.RunPython.noop),
    ]
