# Generated by Django 5.2.8 on 2025-12-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_details_and_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requirements of client (one item per line or markdown list)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='What you will do (one item per line or markdown list)'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
