# Generated by Django 5.2.8 on 2025-12-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_project_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='vibe_tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.vibetag'),
        ),
    ]
