# Generated by Django 5.2.8 on 2025-12-23 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_vibetag_project_vibe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vibe_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_attachments/%Y/%m/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
            ],
        ),
    ]
