# Generated by Django 5.2.8 on 2025-12-23 01:25

from django.db import migrations, models

DEFAULT_VIBE = "Modern, friendly, conversion-focused vibe with clear structure and confident messaging."


def set_vibe_description(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    vibes = {
        "Landing page redesign": "Clean, high-conversion hero with airy spacing, bold typography, and a crisp CTA flow.",
        "API integration for SaaS": "Reliable, security-first integration with clear error states and friendly developer docs.",
        "Brand identity package": "Timeless, versatile brand system with a confident logo, modern palette, and type hierarchy.",
        "E-commerce checkout optimization": "Frictionless checkout with trust cues, fast steps, and Stripe-ready polish.",
        "Dockerize Django project": "Production-ready Docker setup with tidy compose, repeatable dev flow, and clear docs.",
        "Marketing website SEO audit": "Data-driven SEO tune-up with quick wins, technical fixes, and a content roadmap.",
        "Admin dashboard UI": "Utility-first dashboard with clear hierarchy, calm accents, and dense but legible data.",
        "Data cleanup & reporting": "Clean data, sharp metrics, and readable charts with an executive-summary feel.",
        "Mobile app landing + copy": "Warm, punchy messaging with a simple hero, quick benefits, and an easy signup.",
        "CI/CD pipeline setup": "Lean pipeline with fast tests, safe deploy gates, and straightforward documentation.",
    }
    for title, vibe in vibes.items():
        Project.objects.filter(title=title, vibe_description="").update(vibe_description=vibe)
    Project.objects.filter(vibe_description="").update(vibe_description=DEFAULT_VIBE)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_vibe_description_projectattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="vibe_description",
            field=models.TextField(blank=True, default=DEFAULT_VIBE),
        ),
        migrations.RunPython(set_vibe_description, migrations.RunPython.noop),
    ]
