# Generated by Django 5.2.8 on 2025-12-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_update_application_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
