# Generated by Django 5.2.8 on 2025-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_saved_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='availability',
            field=models.CharField(choices=[('immediate', 'Start immediately'), ('1_2_wes', '1-2 weeks'), ('3_4_weeks', '3-4 weeks'), ('month_plus', 'More than a month')], default='immediate', max_length=20),
        ),
    ]
