# Generated by Django 5.2.8 on 2025-12-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _table_exists(cursor, name):
    cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='%s'" % name
    )
    return cursor.fetchone() is not None


def forwards_create_profiles(apps, schema_editor):
    User = apps.get_model("accounts", "CustomUser")
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    FreelancerProfile = apps.get_model("accounts", "FreelancerProfile")

    try:
        Profile = apps.get_model("accounts", "Profile")
    except LookupError:
        Profile = None

    client_user_ids = set()
    with schema_editor.connection.cursor() as cursor:
        if _table_exists(cursor, "projects_project"):
            cursor.execute("SELECT DISTINCT client_id FROM projects_project")
            client_user_ids = {row[0] for row in cursor.fetchall() if row[0] is not None}

    users = list(User.objects.all().only("id", "first_name", "last_name", "email", "role"))

    for user in users:
        if user.role == "client" or user.id in client_user_ids:
            company_name = f"{user.first_name} {user.last_name}".strip()
            if not company_name:
                company_name = user.email.split("@")[0] if user.email else f"Client {user.id}"

            ClientProfile.objects.get_or_create(
                id=user.id,
                defaults={
                    "user_id": user.id,
                    "company_name": company_name,
                    "location": "Unknown",
                    "is_open_to_agencies": False,
                    "hire_rate": 0,
                },
            )

    profile_map = {}
    if Profile is not None:
        for profile in Profile.objects.all():
            profile_map[profile.user_id] = profile

    for user in users:
        if user.role == "freelancer":
            defaults = {
                "user_id": user.id,
                "bio": "",
                "portfolio_website": "",
                "avatar": "",
            }
            profile = profile_map.get(user.id)
            if profile is not None:
                defaults["bio"] = profile.bio or ""
                defaults["portfolio_website"] = profile.portfolio_website or ""
                defaults["avatar"] = profile.avatar or ""

            FreelancerProfile.objects.get_or_create(id=user.id, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_role_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(blank=True, max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("is_open_to_agencies", models.BooleanField(default=False)),
                ("hire_rate", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bio", models.TextField(blank=True)),
                ("portfolio_website", models.URLField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_create_profiles, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
