# Generated by Django 5.2.8 on 2025-12-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_client_and_freelancer_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="portfolio_file",
            field=models.FileField(blank=True, null=True, upload_to="freelancer_portfolios/%Y/%m/"),
        ),
    ]
