# Generated by Django 5.2.8 on 2025-12-27

from decimal import Decimal
from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def seed_freelancer_profile_data(apps, schema_editor):
    FreelancerProfile = apps.get_model("accounts", "FreelancerProfile")

    titles = [
        "Frontend Developer",
        "Backend Developer",
        "Full Stack Developer",
        "UI/UX Designer",
        "Product Designer",
        "Brand Designer",
        "Webflow Specialist",
        "No-Code Developer",
        "Marketing Designer",
        "Content Designer",
    ]

    now = timezone.now()

    for idx, profile in enumerate(
        FreelancerProfile.objects.select_related("user").order_by("id")
    ):
        title = titles[idx % len(titles)]
        rate_value = 25 + (idx % 8) * 12
        hourly_rate = Decimal(f"{rate_value}.00")

        years_back = 1 + (idx % 5)
        days_offset = (idx * 73) % 365
        joined_at = now - timedelta(days=years_back * 365 + days_offset)

        profile.title = title
        profile.hourly_rate = hourly_rate
        profile.joined_at = joined_at
        profile.save(update_fields=["title", "hourly_rate", "joined_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_freelancer_portfolio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="title",
            field=models.CharField(default="Freelancer", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(seed_freelancer_profile_data, migrations.RunPython.noop),
    ]
