# Generated by Django 5.2.8 on 2025-12-27

from django.db import migrations, models


def seed_skills(apps, schema_editor):
    Skill = apps.get_model("accounts", "Skill")
    FreelancerProfile = apps.get_model("accounts", "FreelancerProfile")

    skill_names = [
        "UI Design",
        "UX Research",
        "Product Design",
        "Design Systems",
        "Interaction Design",
        "Wireframing",
        "Prototyping",
        "Information Architecture",
        "User Flows",
        "Usability Testing",
        "Brand Design",
        "Visual Design",
        "Typography",
        "Illustration",
        "Icon Design",
        "Motion Design",
        "Figma",
        "Adobe XD",
        "Sketch",
        "Framer",
        "Webflow",
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Vue.js",
        "Django",
        "REST APIs",
        "SQL",
        "PostgreSQL",
        "Git",
        "Agile",
        "SEO",
        "Content Strategy",
        "Copywriting",
        "Email Marketing",
        "Social Media",
        "Analytics",
        "QA Testing",
        "Project Management",
    ]

    skills = []
    for name in skill_names:
        skill, _ = Skill.objects.get_or_create(name=name)
        skills.append(skill)

    if not skills:
        return

    for idx, profile in enumerate(FreelancerProfile.objects.all().order_by("id")):
        start = idx % len(skills)
        selection = [skills[(start + i) % len(skills)] for i in range(5)]
        profile.skills.set(selection)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_freelancer_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="skills",
            field=models.ManyToManyField(blank=True, related_name="freelancers", to="accounts.skill"),
        ),
        migrations.RunPython(seed_skills, migrations.RunPython.noop),
    ]
