# Generated by Django 5.2.8 on 2025-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_skill_and_freelancer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(default='Not provided', max_length=255),
        ),
    ]
