# Generated by Django 5.2.8 on 2025-12-27 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_freelancerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='weekly_capacity',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
