# Generated by Django 5.2.8 on 2025-12-30 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_freelancerprofile_weekly_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='weekly_capacity',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
